[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title = "isaac_neuromeka"
description="Extension for Isaac Sim usage in Neuromeka"
repository = "https://gitlab.com/neuromeka-group/nrmkq/isaac_neuromeka.git"
keywords = []
category = "robotics"
readme  = "README.md"

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}


[[python.module]]
name = "isaac_neuromeka"
